services:
  sh:
    pull_policy: build
    build:
      context: .
    volumes:
      - ./:/lang

  test:
    pull_policy: build
    build:
      context: .
    volumes:
      - ./:/lang
    entrypoint:
      - make
      - test

  bench:
    pull_policy: build
    build:
      context: .
    volumes:
      - ./:/lang
    entrypoint:
      - make
      - bench
